---
apiVersion: v1
kind: ConfigMap
metadata:
  name: script-configmap
  namespace: hello
data:
  script.py: |
    import os
    from http.server import BaseHTTPRequestHandler, HTTPServer

    class RequestHandler(BaseHTTPRequestHandler):
        def _send_response(self, message):
            self.send_response(200)
            self.send_header('Content-type', 'text/html')
            self.end_headers()
            self.wfile.write(bytes(message, "utf8"))

        def do_GET(self):
            message = os.getenv("GREETING") + ", from " + os.getenv("LOCATION") + "!"
            self._send_response(message)

    if __name__ == "__main__":
        server_address = ('', 8080)
        httpd = HTTPServer(server_address, RequestHandler)
        httpd.serve_forever()
