apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: hello
spec:
  type: NodePort
  selector:
    app: hello
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000
    targetPort: http
