apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hello
  namespace: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  serviceName: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      initContainers:
        - name: init
          image: busybox
          command: ['sh', '-c', 'sleep 30']
      containers:
        - name: hello
          image: python:3.7-slim
          env:
          - name: GREETING
            value: "Hello, World"
          - name: LOCATION
            value: "Space"
          command: ["python", "-m", "http.server", "8080"]
          volumeMounts:
          - name: script-volume
            mountPath: /usr/src/app
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          ports:
            - name: http
              containerPort: 8080
      volumes:
        - name: script-volume
          configMap:
            name: script-configmap
