# This file includes the manifests that 'kind' will utilize to initialize three clusters:
# - `deployer` is designated to host the argocd instance in the future.
# - `paris` and `tokyo` are intended to function as two production clusters in separate regions.

---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: deployer
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 8000
