apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hello
  namespace: hello
spec:
  template:
    spec:
      containers:
      - name: hello
        env:
        - name: LOCATION
          value: "Tokyo"
